# Generated by Django 5.1.1 on 2024-09-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.PositiveSmallIntegerField(choices=[(0, 'Москва'), (1, 'Санкт-Петербург')], default=1, verbose_name='Город')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
    ]
