# Generated by Django 5.1.1 on 2024-09-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.PositiveSmallIntegerField(choices=[(0, 'Москва'), (1, 'Санкт-Петербург')], default=1, verbose_name='Город')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер квартиры')),
                ('square', models.PositiveIntegerField(verbose_name='Площадь')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'default_related_name': 'apartments',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'default_related_name': 'prices',
            },
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Счетчик воды',
                'verbose_name_plural': 'Счетчики воды',
                'default_related_name': 'water_meters',
            },
        ),
        migrations.CreateModel(
            name='WaterMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.PositiveSmallIntegerField(choices=[(None, 'Не выбрано'), (0, 'Январь'), (1, 'Февраль'), (2, 'Март'), (3, 'Апрель'), (4, 'Май'), (5, 'Июнь'), (6, 'Июль'), (7, 'Август'), (8, 'Сентябрь'), (9, 'Октябрь'), (10, 'Ноябрь'), (11, 'Декабрь')], verbose_name='Месяц')),
                ('reading', models.PositiveSmallIntegerField(verbose_name='Показания')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.watermeter', verbose_name='Счетчик')),
            ],
            options={
                'verbose_name': 'Показания счетчика',
                'verbose_name_plural': 'Показании счетчика',
                'default_related_name': 'reading',
                'constraints': [models.UniqueConstraint(fields=('meter', 'date'), name='core_watermeterreading_unique_pair_of_meter_and_date', violation_error_message='На этот месяц показания счетчика уже записаны.')],
            },
        ),
    ]
