# Generated by Django 5.1.1 on 2024-09-07 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.PositiveIntegerField(verbose_name='Площадь')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'default_related_name': 'apartments',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'default_related_name': 'prices',
            },
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Счетчик воды',
                'verbose_name_plural': 'Счетчики воды',
                'default_related_name': 'water_meters',
            },
        ),
        migrations.CreateModel(
            name='WaterMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('reading', models.PositiveSmallIntegerField(verbose_name='Показания')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.watermeter', verbose_name='Счетчик')),
            ],
            options={
                'verbose_name': 'Показания счетчика',
                'verbose_name_plural': 'Показании счетчика',
                'default_related_name': 'reading',
                'unique_together': {('meter', 'date')},
            },
        ),
    ]
